# Generated by Django 5.2.5 on 2025-09-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_payments_payment_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='chapa_checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
