services:
  - type: web
    name: alx-travel-app
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn alx_travel_app.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: alx-travel-app.onrender.com
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
    staticPublishPath: ./alx_travel_app/staticfiles
    staticMappings:
      - urlPath: /static/
        directory: ./alx_travel_app/staticfiles

  - type: redis
    name: redis
    plan: free
